CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    login VARCHAR(25) NOT NULL,
    password BYTEA NOT NULL
);

CREATE UNIQUE INDEX UX_login ON public.users(login);